### ISSUE TITLE
Structure which leads to one inductive constructors are not structures in Lean

### ISSUE THREAD

**Issue by RaitoBezarius** [AeneasVerif/aeneas#178]
Consider:

```rust
struct AVLNode<T> {
    value: T,
    left: AVLTree<T>,
    right: AVLTree<T>,
    height: usize,
}
```

This gets extracted as an inductive with a single constructor instead of a structure in Lean:

```lean
/- [avl_verification::AVLNode]
   Source: 'src/main.rs', lines 33:0-33:17 -/
inductive AVLNode (T : Type) :=
| mk : T → Option (AVLNode T) → Option (AVLNode T) → Usize → AVLNode T
```

It's a bit pesky to use because any refactor will cause havoc in the destructurations and we need to generate our projections manually in the Lean side.

**Comment by R1kM** [comment]
The Lean backend supports extracting Rust structs to structures.
The problem here is that Rust struct is defined recursively, as AVLTree is defined as an option of AVLNode; Lean 4 does not seem to support recursive structures, hence the need to compile it to an inductive.

After discussion with @sonmarcho , one solution to retrieve a similar behavior as structures would be to also generate projectors when extracting recursive structs. I opened #185 to track this
