### ISSUE TITLE
Test crates fail to build in CI

### ISSUE THREAD

**Issue by sonmarcho** [AeneasVerif/aeneas#296]
See [this](https://github.com/AeneasVerif/aeneas/blob/main/tests/src/betree/Cargo.toml)

**Comment by Nadrieril** [comment]
That's not exactly the issue. The test runner simply doesn't run on crates in CI, because usually crates are for dependencies and those need to be built separately with `charon.extractCrateWithCharon`. We can change that, and then the test runner will be able to handle library and binary crates the same.
