### ISSUE TITLE
Name clash detected error when method and trait method have the same name

### ISSUE THREAD

**Issue by zhassan-aws** [AeneasVerif/aeneas#87]
For the following program:
```rust
trait T {
    fn f(&self);
}

struct Foo {
    x: i32,
}

impl Foo {
    fn f(&self) { }
}

impl T for Foo {
    fn f(&self) { }
}

fn main() { }
```
Aeneas complains of a name clash:
```bash
$ charon
   Compiling clash v0.1.0 (/home/ubuntu/examples/aeneas/clash)
[ INFO charon_driver::export:106] [gexport]: Generated the file: /home/ubuntu/examples/aeneas/clash/clash.llbc
    Finished release [optimized] target(s) in 0.15s
$ aeneas -backend lean clash.llbc 
[Info ] Imported: clash.llbc
[Error] Name clash detected: the following identifiers are bound to the same name "Foo.f":
- clash::{clash::Foo}::f
- clash::{clash::Foo#1}::f
You may want to rename some of your definitions, or report an issue.
Uncaught exception:
  
  (Failure
    "Name clash detected: the following identifiers are bound to the same name \"Foo.f\":\
   \n- clash::{clash::Foo}::f\
   \n- clash::{clash::Foo#1}::f\
   \nYou may want to rename some of your definitions, or report an issue.")

Raised at Aeneas__ExtractBase.report_name_collision in file "ExtractBase.ml", line 266, characters 28-47
Called from Aeneas__ExtractBase.names_map_add in file "ExtractBase.ml", line 291, characters 2-51
Called from Aeneas__ExtractBase.names_maps_add in file "ExtractBase.ml", line 422, characters 20-67
Called from Aeneas__ExtractBase.ctx_add in file "ExtractBase.ml", line 662, characters 19-69
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from Aeneas__Translate.translate_crate in file "Translate.ml", line 997, characters 4-761
Called from Dune__exe__Main in file "Main.ml", line 274, characters 6-58
```
Using the same name is legal in Rust: https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name

**Comment by ClaudineRiehl** [comment]
I'm putting the code generated by Aeneas for the reference here:
```lean
structure T (Self : Type) where
  f : Self → Result Unit

structure Foo where
  x : I32

/- This is the function from `impl Foo` -/
def Foo.f (self : Foo) : Result Unit :=
  Result.ret ()

/- This is the function from `impl T for Foo` -/
def Foo.f (self : Foo) : Result Unit :=
  Result.ret ()

def TclashFooInst : T Foo := {
  f := Foo.f
}
```

Yes indeed, Rust is very lax when it comes to name clashes because it uses types to disambiguate, and this has been a recurring issue when generating code from Rust.
Here the issue is that Rust can disambiguate the `f` coming from the `impl Foo` from the `f` coming from the `impl T for Foo` (provided we add some annotations like `(T as Foo).f` at times). In particular, generally speaking, it is ok to have several `impl` blocks defining functions with the same name.

When generating code however, we can't do the same (there is no such thing as an `impl` block in Lean) and we have the find the right balance between generating complicated names to disambiguate the different definitions, and keeping names short for the purpose of convenience. I'm trying to keep names as short as possible while detecting clashes at code generation time.

I think the solution for this issue is to prefix the name of the methods defined for trait implementations with the name of the trait instance (for now I've been using the name of the type for which we instantiate the trait). The end of the snippet above would be updated to:
```lean
/- This is the function from `impl T for Foo` -/
def TclashFooInst.f (self : Foo) : Result Unit :=
  Result.ret ()

def TclashFooInst : T Foo := {
  f := TclashFooInst.f
}
```

As a side note: if you use the option `-k` you can force Aeneas to ignore such errors and generate code anyway. There are other kind of errors which will be ignored, and we are currently updating the code so that in most situations Aeneas will not abort on the first error and will at least try to generate files with holes. This is useful if you encounter a blocking issue and want to go forward (you can manually edit the files while waiting for a fix).

**Comment by sonmarcho** [comment]
I'm putting the code generated by Aeneas for the reference here:
```lean
structure T (Self : Type) where
  f : Self → Result Unit

structure Foo where
  x : I32

/- This is the function from `impl Foo` -/
def Foo.f (self : Foo) : Result Unit :=
  Result.ret ()

/- This is the function from `impl T for Foo` -/
def Foo.f (self : Foo) : Result Unit :=
  Result.ret ()

def TclashFooInst : T Foo := {
  f := Foo.f
}
```

Yes indeed, Rust is very lax when it comes to name clashes because it uses types to disambiguate, and this has been a recurring issue when generating code from Rust.
Here the issue is that Rust can disambiguate the `f` coming from the `impl Foo` from the `f` coming from the `impl T for Foo` (provided we add some annotations like `(T as Foo).f` at times). In particular, generally speaking, it is ok to have several `impl` blocks defining functions with the same name.

When generating code however, we can't do the same (there is no such thing as an `impl` block in Lean) and we have the find the right balance between generating complicated names to disambiguate the different definitions, and keeping names short for the purpose of convenience. I'm trying to keep names as short as possible while detecting clashes at code generation time.

I think the solution for this issue is to prefix the name of the methods defined for trait implementations with the name of the trait instance (for now I've been using the name of the type for which we instantiate the trait). The end of the snippet above would be updated to:
```lean
/- This is the function from `impl T for Foo` -/
def TclashFooInst.f (self : Foo) : Result Unit :=
  Result.ret ()

def TclashFooInst : T Foo := {
  f := TclashFooInst.f
}
```

As a side note: if you use the option `-k` you can force Aeneas to ignore such errors and generate code anyway. There are other kind of errors which will be ignored, and we are currently updating the code so that in most situations Aeneas will not abort on the first error and will at least try to generate files with holes. This is useful if you encounter a blocking issue and want to go forward (you can manually edit the files while waiting for a fix).

**Comment by sonmarcho** [comment]
Solved by https://github.com/AeneasVerif/aeneas/pull/88

Aeneas now generates the following code:
```lean
/- Trait declaration: [clash::T] -/
structure T (Self : Type) where
  f : Self → Result Unit

/- [clash::Foo] -/
structure Foo where
  x : I32

/- [clash::{clash::Foo}::f] -/
def Foo.f (self : Foo) : Result Unit :=
  Result.ret ()

/- [clash::{(clash::T for clash::Foo)#1}::f] -/
def TclashFoo.f (self : Foo) : Result Unit :=
  Result.ret ()

/- Trait implementation: [clash::{(clash::T for clash::Foo)#1}] -/
def TclashFoo : T Foo := {
  f := TclashFoo.f
}
```
